#!/usr/bin/perl

my $template = <<'END_TEMPLATE';
	location /project/[PROJ]
		rewrite ^/.* https://$server_name/+[ID] permanent;
	}
END_TEMPLATE

my $links = <<'END_LINKS';
https://beagleboard.org/project/tor/,134e59
https://beagleboard.org/project/hbp/,e79e8f
https://beagleboard.org/project/POST+for+beagle+board/,1814de
https://beagleboard.org/project/holodome/,16c3b6
https://beagleboard.org/project/linux_education/,fd270f
https://beagleboard.org/project/testkiosk/,d081ea
https://beagleboard.org/project/VermaVocoder/,a043fb
https://beagleboard.org/project/Lox/,2d0e32
https://beagleboard.org/project/Bowld/,d38b72
https://beagleboard.org/project/beaglebone-net-radio/,401c11
https://beagleboard.org/project/Beagle+Communicator/,60ab8c
https://beagleboard.org/project/Replicape+Plus/,5ac93e
https://beagleboard.org/project/Sundial/,97a18a
https://beagleboard.org/project/bug/,4eb994
https://beagleboard.org/project/Beagle+goes+UHVO/,a4dbb6
https://beagleboard.org/project/Video+Switcher/,df3755
https://beagleboard.org/project/BBBDevStation/,4ea6ab
https://beagleboard.org/project/Beagle-Borg/,ac0c55
https://beagleboard.org/project/bitson-cape/,94b33b
https://beagleboard.org/project/bbbprimer/,53f988
https://beagleboard.org/project/ember/,e52bad
https://beagleboard.org/project/bbb-mainline-linux-kernel/,806c9b
https://beagleboard.org/project/X15/,91ef5d
https://beagleboard.org/project/1593HAMBONEBK/,734973
https://beagleboard.org/project/ALIP+%28Obsoleted+by+Linaro%29/,a876b7
https://beagleboard.org/project/CamCon/,ff867e
https://beagleboard.org/project/opensuse_bbb/,e316e8
https://beagleboard.org/project/awsiot/,b68072
https://beagleboard.org/project/kinect_fan/,404d7e
https://beagleboard.org/project/nghost+for+head+unit/,03ab86
https://beagleboard.org/project/BeagleWatch/,2ca6dd
https://beagleboard.org/project/bbp/,e3fbd8
https://beagleboard.org/project/The+Space+Station/,a15818
https://beagleboard.org/project/automatedtubularmusicthingy/,bc681b
https://beagleboard.org/project/chickencoopdoor/,5cbe5f
https://beagleboard.org/project/B-NFDS/,af8a0d
https://beagleboard.org/project/heatsink-bbb-enclosure/,463d29
https://beagleboard.org/project/picknpaste/,01106a
https://beagleboard.org/project/Volumio/,151160
https://beagleboard.org/project/libpruio/,b9f5c8
https://beagleboard.org/project/OPENOMAP/,251b16
https://beagleboard.org/project/disptec/,f196ce
https://beagleboard.org/project/aihro/,755923
https://beagleboard.org/project/fsl3d/,7e7c67
https://beagleboard.org/project/tiser/,300663
https://beagleboard.org/project/navsol/,f7097f
https://beagleboard.org/project/ledgames/,424215
https://beagleboard.org/project/ViFFF-024/,acf2be
https://beagleboard.org/project/kali/,3fda7b
https://beagleboard.org/project/OBD1+Honda+/,2c60c6
https://beagleboard.org/project/GPS/,ba781b
https://beagleboard.org/project/lowcost-robot/,d92b01
https://beagleboard.org/project/feet/,afd7d1
https://beagleboard.org/project/digital+pyrometer/,b4f26f
https://beagleboard.org/project/beagle-ros/,0b6259
https://beagleboard.org/project/botspeak/,24e7e8
https://beagleboard.org/project/pru/,0e7412
https://beagleboard.org/project/Meego+on+Beagleboard/,70b817
https://beagleboard.org/project/Oled/,7c1a10
https://beagleboard.org/project/lasersaur/,1bb3fa
https://beagleboard.org/project/virtualT/,b8590e
https://beagleboard.org/project/BeagleROS/,b7f0b8
https://beagleboard.org/project/CrashBone/,2d41f6
https://beagleboard.org/project/internetspeed/,c26afa
https://beagleboard.org/project/freebsd-bgb/,e7b5a5
https://beagleboard.org/project/traffic/,7649cf
https://beagleboard.org/project/ibmsensortag/,7f30ab
https://beagleboard.org/project/aamfl/,aee796
https://beagleboard.org/project/Gnome/,d70e3a
https://beagleboard.org/project/evb/,18df24
https://beagleboard.org/project/podtique/,67f818
https://beagleboard.org/project/cylonjs/,22a7bf
https://beagleboard.org/project/DistributedTemperature/,dd07eb
https://beagleboard.org/project/novus/,853e82
https://beagleboard.org/project/beaglephone/,fbf405
https://beagleboard.org/project/Robotics+Bus/,b016ee
https://beagleboard.org/project/javascript-tricks/,08f392
https://beagleboard.org/project/BBBabb/,ac5006
https://beagleboard.org/project/LAND+ROVER/,191f69
https://beagleboard.org/project/USB+download/,676036
https://beagleboard.org/project/0xdroid/,e5baf9
https://beagleboard.org/project/bbcarputer/,64a1d9
https://beagleboard.org/project/PupLC/,1ff7cd
https://beagleboard.org/project/djvideomixer/,7db19e
https://beagleboard.org/project/Beagle-Copter/,f30e88
https://beagleboard.org/project/bbbarduinouno/,b02236
https://beagleboard.org/project/mother/,9908bb
https://beagleboard.org/project/COUGAR/,58ffa4
https://beagleboard.org/project/mainline-capemgr-patchset/,fc9779
https://beagleboard.org/project/babymonitor/,27f5bf
https://beagleboard.org/project/beaglemnt/,77d51d
https://beagleboard.org/project/beaglelogic/,862921
https://beagleboard.org/project/wiringBone/,1ac69b
https://beagleboard.org/project/ps1rfid/,7ce474
https://beagleboard.org/project/modulbox/,9f4296
https://beagleboard.org/project/uniBBB/,90a304
https://beagleboard.org/project/BBB_EEProm_Binary_File_Gen/,254222
https://beagleboard.org/project/escape/,451d06
https://beagleboard.org/project/gamingcape/,6a38e1
https://beagleboard.org/project/wrx/,e969a4
https://beagleboard.org/project/freedombone/,5fd6f7
https://beagleboard.org/project/LearningBB/,d0f4bb
https://beagleboard.org/project/BLACKlink/,0964df
https://beagleboard.org/project/opensprinkler/,9c67df
https://beagleboard.org/project/BeagleMono/,792894
https://beagleboard.org/project/Home+automation/,3ccaf5
https://beagleboard.org/project/anidees-bbb-case/,3da903
https://beagleboard.org/project/openqpcr/,a98ae5
https://beagleboard.org/project/dart/,22faed
https://beagleboard.org/project/iomotix/,ea813b
https://beagleboard.org/project/cnc-pump/,972638
https://beagleboard.org/project/oel/,4b9f6e
https://beagleboard.org/project/portable+bioinformatics+tool/,827d91
https://beagleboard.org/project/Minix3+support/,6dd3ce
https://beagleboard.org/project/bbb-bicolor-matrix/,4cb7a5
https://beagleboard.org/project/tiesr/,badaa1
https://beagleboard.org/project/asterisk/,54f792
https://beagleboard.org/project/prucape/,57413a
https://beagleboard.org/project/BREC/,97099a
https://beagleboard.org/project/OpenVLC/,c9d4a1
https://beagleboard.org/project/U-Boot+%28V1%29/,2adf7f
https://beagleboard.org/project/Omek+Beckon+SDK++/,e8eae1
https://beagleboard.org/project/java/,3160a6
https://beagleboard.org/project/beaglebonebsp/,b07422
https://beagleboard.org/project/bonescript/,b90401
https://beagleboard.org/project/bcc/,2a955c
https://beagleboard.org/project/metabone/,2ea337
https://beagleboard.org/project/CryptoCape/,4e2955
https://beagleboard.org/project/Micro-stepper/,92fc3d
https://beagleboard.org/project/riscos/,ae8bbc
https://beagleboard.org/project/BoneTagzzz/,d2d080
https://beagleboard.org/project/QNX+Neutrino+on+OMAP/,2610b1
https://beagleboard.org/project/getting-started-book/,19e029
https://beagleboard.org/project/PWM+driver+for+Beagle+Board/,1294e7
https://beagleboard.org/project/BeagleDrone/,cd4648
https://beagleboard.org/project/omap-rt-patch/,9fe9a8
https://beagleboard.org/project/Irrlicht/,275225
https://beagleboard.org/project/WiRe/,f64baf
https://beagleboard.org/project/beagle-wacom/,e83d89
https://beagleboard.org/project/BeagleConf/,25d6a5
https://beagleboard.org/project/USB_Hotplugging/,f42d45
https://beagleboard.org/project/ntopng/,446ed8
https://beagleboard.org/project/RGB+LED+%28Hello+World+for+BBB%29/,64f246
https://beagleboard.org/project/RTT-Scores/,f51219
https://beagleboard.org/project/disoreint-pyramid/,f85adb
https://beagleboard.org/project/16x16+Beagle+Matrix/,d9d922
https://beagleboard.org/project/clozure/,a12b76
https://beagleboard.org/project/Autonomous+Robot/,4a2450
https://beagleboard.org/project/PRUJTAG/,f89204
https://beagleboard.org/project/The+Deckle/,9c9e96
https://beagleboard.org/project/beagleboot/,a9a4c4
https://beagleboard.org/project/opensuse/,abde5c
https://beagleboard.org/project/omapconf/,3dc10f
https://beagleboard.org/project/Xvisor/,4add9c
https://beagleboard.org/project/BeagleRB/,5691a3
https://beagleboard.org/project/OpenCV-+Haar+Training+on+DSP/,3e906b
https://beagleboard.org/project/Human++Identification+System+/,c54437
https://beagleboard.org/project/Data+Acquisition+Platform/,31c0e3
https://beagleboard.org/project/DAISI/,958ed6
https://beagleboard.org/project/BeagleBoard+Validation/,2193f5
https://beagleboard.org/project/Hardware+Validation/,22b1e0
https://beagleboard.org/project/BOB/,79c40a
https://beagleboard.org/project/meego4beagle/,8ddbef
https://beagleboard.org/project/Ethernet+combo+board/,a763eb
https://beagleboard.org/project/SpheViSy/,c5c6d1
https://beagleboard.org/project/RaDromotic/,e27f8a
https://beagleboard.org/project/PostBot/,0c8ab7
https://beagleboard.org/project/BeagleHome/,c497da
https://beagleboard.org/project/beagle+tracker/,de158d
https://beagleboard.org/project/U-Boot+V2/,cdfb85
https://beagleboard.org/project/reacTIVision/,caeb00
https://beagleboard.org/project/puppybits/,659bff
https://beagleboard.org/project/linuxlink/,66f39c
https://beagleboard.org/project/fedora/,ff255b
https://beagleboard.org/project/Project+Kennel/,deecdd
https://beagleboard.org/project/tianocore/,b4c601
https://beagleboard.org/project/Beagle-Eye/,b0db7f
https://beagleboard.org/project/BeagleTick/,b58aa5
https://beagleboard.org/project/Beagle-Arduino+hybrid+robot/,09af36
https://beagleboard.org/project/TCF+agent+port/,63d661
https://beagleboard.org/project/miniECG/,390686
https://beagleboard.org/project/BuildBeagle/,f121f9
https://beagleboard.org/project/BeagleBoy/,34c7f3
https://beagleboard.org/project/nodered/,843584
https://beagleboard.org/project/boris/,2c25d3
https://beagleboard.org/project/solar+powered+beagle/,378ed9
https://beagleboard.org/project/robotic-projects-book/,c46264
https://beagleboard.org/project/multichannel-audio-system/,bc7c1e
https://beagleboard.org/project/home-security-book/,59c980
https://beagleboard.org/project/Revolt2405/,052574
https://beagleboard.org/project/PowerBar/,0c5492
https://beagleboard.org/project/octoscroller/,0f56c6
https://beagleboard.org/project/Beagle+Extension/,c0ceb0
https://beagleboard.org/project/GStreamer_TI/,15518b
https://beagleboard.org/project/maemo/,73ef40
https://beagleboard.org/project/evmonbeagle/,509555
https://beagleboard.org/project/qemu-omap3/,dc9425
https://beagleboard.org/project/Aptina+Drivers/,2a91a6
https://beagleboard.org/project/BuddyBot/,fc4012
https://beagleboard.org/project/Digiboard/,d8b3c7
https://beagleboard.org/project/BBPeripheralEx/,50a7cd
https://beagleboard.org/project/GpioTest/,c09ddd
https://beagleboard.org/project/BBB_HS_USB/,274625
https://beagleboard.org/project/HomeEnergy/,7edafa
https://beagleboard.org/project/OTR/,ea26c3
https://beagleboard.org/project/BeaglesRide.org/,b2fd20
https://beagleboard.org/project/beagleSQL/,67f6e9
https://beagleboard.org/project/Cosmic+Board+%28phyCORE-AM335x%29/,c0e524
https://beagleboard.org/project/beaglesense/,ad8e4a
https://beagleboard.org/project/home-automation-book/,6dec15
https://beagleboard.org/project/Beagle-Mobile/,d01e20
https://beagleboard.org/project/webLightSwitch/,93551d
https://beagleboard.org/project/virtualhere/,6f47ff
https://beagleboard.org/project/openRemote+and+BBB/,baea30
https://beagleboard.org/project/heliUAV/,fe2caa
https://beagleboard.org/project/beaglebell/,856ffc
https://beagleboard.org/project/MineNinja/,fe993e
https://beagleboard.org/project/SensorCape/,1c197c
https://beagleboard.org/project/temperature+server/,f1f27c
https://beagleboard.org/project/nerves/,26e743
https://beagleboard.org/project/bbot/,cefbc7
https://beagleboard.org/project/gsoc-13-adc/,f3f469
https://beagleboard.org/project/Swissbone/,9eb622
https://beagleboard.org/project/Mentor+Embedded+Linux/,0d5a79
https://beagleboard.org/project/freebsd/,eb6cff
https://beagleboard.org/project/RFIDADP/,c0f9d5
https://beagleboard.org/project/Reprap+System/,f8f24f
https://beagleboard.org/project/OKL4+LCD/,5dba04
https://beagleboard.org/project/Nitrogen/,9db3b8
https://beagleboard.org/project/ModemBoard/,c26ed9
https://beagleboard.org/project/solartracker/,a02952
https://beagleboard.org/project/Dubhouse1/,528965
https://beagleboard.org/project/VSCP/,719b3c
https://beagleboard.org/project/BeagleQ/,4a9903
https://beagleboard.org/project/biltter-bike/,24c54a
https://beagleboard.org/project/nullDC_Beagle/,732165
https://beagleboard.org/project/ttylinux/,c93e7b
https://beagleboard.org/project/ProtoBone/,00a9f9
https://beagleboard.org/project/beaglebone-net%27-radio/,a2dd58
https://beagleboard.org/project/likecounter/,fc0d9d
https://beagleboard.org/project/BBSDR/,122350
https://beagleboard.org/project/BeagleTroll/,c62084
https://beagleboard.org/project/livebone/,9d13ae
https://beagleboard.org/project/AUV/,2865da
https://beagleboard.org/project/Windows+CE+Beagleboard/,634217
https://beagleboard.org/project/BeagleBrick/,42cdce
https://beagleboard.org/project/bb+dd-wrt/,ec2d29
https://beagleboard.org/project/AstroBeagle/,9d7792
https://beagleboard.org/project/elinux-tcl/,6d266c
https://beagleboard.org/project/AGV/,da2afe
https://beagleboard.org/project/buildroot/,319204
https://beagleboard.org/project/twitter-matrix/,7d13f2
https://beagleboard.org/project/opensmartmeter/,9692f1
https://beagleboard.org/project/MyGTee/,93aea1
https://beagleboard.org/project/POSBeagle/,4b60dc
https://beagleboard.org/project/Portable_Medical_Telemetry/,45d6a4
https://beagleboard.org/project/BeagleTraveler/,87d30e
https://beagleboard.org/project/BeagleLocTemp/,62f270
https://beagleboard.org/project/C6Run/,0422a2
https://beagleboard.org/project/beaglevision/,ad64a4
https://beagleboard.org/project/Mamona+On+Beagle/,405688
https://beagleboard.org/project/CHARTER+Project+Wirless+ECG+/,0bed75
https://beagleboard.org/project/HelloBone/,2722c3
https://beagleboard.org/project/Synergy%2B%2B/,64288d
https://beagleboard.org/project/BeagleCANBoard/,502ce3
https://beagleboard.org/project/vangalapraveenkumar/,6322c6
https://beagleboard.org/project/linux/,24f86b
https://beagleboard.org/project/QRVC/,1107b8
https://beagleboard.org/project/hardhat/,231349
https://beagleboard.org/project/AMC/,46f55d
https://beagleboard.org/project/beagleboard-lcd/,6c0303
https://beagleboard.org/project/CamCast/,ab9f49
https://beagleboard.org/project/Minilaptop/,20aacd
https://beagleboard.org/project/Building_Qt/,d84bd9
https://beagleboard.org/project/BADTASTICALLY_AWESOME/,d4a7df
https://beagleboard.org/project/stache/,a241e1
https://beagleboard.org/project/ipv6bluetooth/,5e8a71
https://beagleboard.org/project/fbtft-linux-44-kernel/,5fce2a
https://beagleboard.org/project/azure/,af45af
https://beagleboard.org/project/fbtft-drivers-ti-inux-41/,6e9e22
https://beagleboard.org/project/xen_i2c/,51b647
https://beagleboard.org/project/pxf/,9214c7
https://beagleboard.org/project/opencv+acceleration/,a17d8f
https://beagleboard.org/project/MeaProcess/,3fd62e
https://beagleboard.org/project/linaro-android/,94fccd
https://beagleboard.org/project/MachineKit/,584b2c
https://beagleboard.org/project/BE-Wear/,8a82c4
https://beagleboard.org/project/EmbeddedHost/,7b66af
https://beagleboard.org/project/erle-brain/,28bc69
https://beagleboard.org/project/gnupru/,c0b677
https://beagleboard.org/project/freertos/,337768
https://beagleboard.org/project/BeagleWrite/,93382f
https://beagleboard.org/project/Rocamo/,d270f5
https://beagleboard.org/project/AQUABOT/,ac95a6
https://beagleboard.org/project/logi-bone-fpga/,b0901d
https://beagleboard.org/project/BBConsole/,7590c7
https://beagleboard.org/project/linaro-ubuntu/,d8deea
https://beagleboard.org/project/easyBlack/,f0b54d
https://beagleboard.org/project/starterware/,8d1ecd
https://beagleboard.org/project/se-michigan-meetup/,a8703e
https://beagleboard.org/project/Pillreminder/,806a16
https://beagleboard.org/project/show/,7d1a69
https://beagleboard.org/project/Plan+9+OS/,951539
https://beagleboard.org/project/prduino/,5ade22
https://beagleboard.org/project/PyBBIO/,24108a
https://beagleboard.org/project/BBB/,40ae2a
https://beagleboard.org/project/bbb_i2c/,90cbce
https://beagleboard.org/project/WinCE7+BSP+for+BeagleBoard-XM/,3ffafb
https://beagleboard.org/project/omapandroid/,1d7dda
https://beagleboard.org/project/rtems/,b231b3
https://beagleboard.org/project/LightZord/,2939b6
https://beagleboard.org/project/bacon/,3242c7
https://beagleboard.org/project/gobot/,1505bf
https://beagleboard.org/project/usbscope/,18a057
https://beagleboard.org/project/website/,5ed4d4
https://beagleboard.org/project/T-bone/,e2ddd5
https://beagleboard.org/project/Ubuntu/,6c7f26
https://beagleboard.org/project/Beagle-Solar-A-Car/,6b9cda
https://beagleboard.org/project/smalltalk/,f2f849
https://beagleboard.org/project/FlyingBone/,2685e0
https://beagleboard.org/project/BeadaFrame/,8f9aaf
https://beagleboard.org/project/nh5cape/,46f4bc
https://beagleboard.org/project/ZigBeagle/,cf7e28
https://beagleboard.org/project/OpenRTDynamics/,5daf12
https://beagleboard.org/project/amsdk/,b3436b
https://beagleboard.org/project/android/,2bbec0
https://beagleboard.org/project/POTS/,68f65c
https://beagleboard.org/project/Gentoo/,207b09
https://beagleboard.org/project/userspace-arduino/,44f411
https://beagleboard.org/project/usbsniffer/,ba62d2
https://beagleboard.org/project/picoFlamingo/,ffa9d5
https://beagleboard.org/project/dsp-rpc-posix/,ff7766
https://beagleboard.org/project/Apertus/,54c8da
https://beagleboard.org/project/OMAP35x+SMP/,e2eab7
https://beagleboard.org/project/beagleepd/,ba083f
https://beagleboard.org/project/Beagle+SDR/,d725f4
https://beagleboard.org/project/MSU+ECE480/,2d772a
https://beagleboard.org/project/computer-vision/,9b014a
https://beagleboard.org/project/Beagledroid/,24c966
https://beagleboard.org/project/BeagleBot/,5c7f64
https://beagleboard.org/project/PIXHAWK/,4af709
https://beagleboard.org/project/Beagle+wiki/,d8e9b4
https://beagleboard.org/project/ffmpeg/,1a3c2e
https://beagleboard.org/project/documentation/,8ce4ca
https://beagleboard.org/project/adclock/,9e0078
https://beagleboard.org/project/CAN/,47f1c8
https://beagleboard.org/project/palm/,905e71
https://beagleboard.org/project/Xen_ARM_PV/,ea1cef
https://beagleboard.org/project/Bottleing+plant/,f76c1c
https://beagleboard.org/project/USS/,8d6bc7
https://beagleboard.org/project/makoserver.net/,cfa640
https://beagleboard.org/project/wifiradio1/,62f6d4
https://beagleboard.org/project/yaler/,452bbc
https://beagleboard.org/project/BitTorrent+Download+Console/,f0fe50
https://beagleboard.org/project/Lapdock/,f30e80
https://beagleboard.org/project/Motion+Control/,82bafa
https://beagleboard.org/project/decbox/,654c43
https://beagleboard.org/project/desc-camera/,9c9379
https://beagleboard.org/project/Traffiic+Light/,243fec
https://beagleboard.org/project/BBMPEB/,434a7e
https://beagleboard.org/project/Beagle3GRouter/,390c87
https://beagleboard.org/project/TEND+Rover+Project/,ecaf3c
https://beagleboard.org/project/LVDS+LCD/,285c66
https://beagleboard.org/project/aj/,35bbf9
https://beagleboard.org/project/video-notes/,94dbaf
https://beagleboard.org/project/BeagleScanSpec/,0b2c46
https://beagleboard.org/project/openlink/,f6b8ac
https://beagleboard.org/project/ccrma/,58451f
https://beagleboard.org/project/Beagleboard+Windows+CE+BSP/,ad7b28
https://beagleboard.org/project/E-CarPC/,d409a0
https://beagleboard.org/project/BeagleEye/,eca262
https://beagleboard.org/project/B-UTV/,3190bd
https://beagleboard.org/project/beaglebook/,f791ad
https://beagleboard.org/project/BeagleBox/,5f1408
https://beagleboard.org/project/dragonphone/,a0bed9
https://beagleboard.org/project/beaglepod/,0b7222
https://beagleboard.org/project/TiroKart/,1e7425
https://beagleboard.org/project/VCWC/,6f05ff
https://beagleboard.org/project/Earth+Jukebox/,f5b72c
https://beagleboard.org/project/GGrB/,cd9036
https://beagleboard.org/project/BeaglePLC/,df67ea
https://beagleboard.org/project/Speed-Reader/,ca5141
https://beagleboard.org/project/Asil/,6a7e54
https://beagleboard.org/project/symbian/,d94b2f
https://beagleboard.org/project/Autonomous+control%2Cand+target+/,0ba044
https://beagleboard.org/project/OMAP+Emulator/,342ca5
https://beagleboard.org/project/BIVD/,dd3c1d
https://beagleboard.org/project/FETCH/,792c1a
https://beagleboard.org/project/ESITeam/,5c4f87
https://beagleboard.org/project/schooldog/,679b0a
https://beagleboard.org/project/HDDM/,5da697
https://beagleboard.org/project/BeagleLAB/,e62347
https://beagleboard.org/project/remoteBillBoard/,64a6c9
https://beagleboard.org/project/BeaglePack/,263249
https://beagleboard.org/project/handheld_lab/,ffe411
https://beagleboard.org/project/Android+SDIO+WIFI/,5555a4
https://beagleboard.org/project/HappyCP/,9f9bc4
https://beagleboard.org/project/TUD%3AOS+on+the+Beagleboard/,7a5723
https://beagleboard.org/project/fbtft-drivers-for-linux-38/,fc47fc
https://beagleboard.org/project/bb100/,bb4b42
https://beagleboard.org/project/shieldio/,f9cb3b
https://beagleboard.org/project/adafruit-bbb-case/,f1a6e3
https://beagleboard.org/project/chromium/,80fdf1
https://beagleboard.org/project/visualgdb/,85731a
https://beagleboard.org/project/artoo/,d56dc3
https://beagleboard.org/project/WEBB/,093614
https://beagleboard.org/project/rfid-authentication-for-hacker/,b73629
https://beagleboard.org/project/James/,1de2a3
https://beagleboard.org/project/Handhelds+Mojo/,bcaa2a
https://beagleboard.org/project/beagleboard-matlab-book/,40fdfa
https://beagleboard.org/project/usingswift/,ed72ca
https://beagleboard.org/project/swift+bones/,c6c5ff
https://beagleboard.org/project/OpenOCD+OMAP3+JTAG+support/,91f08c
https://beagleboard.org/project/SoilAnalyzer/,4bc29c
https://beagleboard.org/project/cookbook/,e44573
https://beagleboard.org/project/stantor_BBB_v03/,2ee60c
https://beagleboard.org/project/RT+DACHSview-Bone/,5eb73b
https://beagleboard.org/project/A+Home+Security+System/,95d5ab
https://beagleboard.org/project/6LBR/,08f765
https://beagleboard.org/project/BeaglePilot/,9de5d9
https://beagleboard.org/project/BeagleBird/,db6a93
https://beagleboard.org/project/beagleham/,94606c
https://beagleboard.org/project/EECCD/,51a675
https://beagleboard.org/project/Replicape/,922e72
https://beagleboard.org/project/openrov/,daa1c8
https://beagleboard.org/project/apstability/,0b38f3
https://beagleboard.org/project/Debian/,ab3bb7
https://beagleboard.org/project/3dhubsbeagleboard/,ad8bd8
https://beagleboard.org/project/PADS/,cc5c24
https://beagleboard.org/project/sparkfun-case-clear/,a72c7c
https://beagleboard.org/project/pocketnc/,d11f1d
https://beagleboard.org/project/jailinux/,6cee4c
https://beagleboard.org/project/jilia/,19b708
https://beagleboard.org/project/mikrobus/,75f149
https://beagleboard.org/project/3dprinting/,149efb
https://beagleboard.org/project/mathworksbbb/,eb9c54
https://beagleboard.org/project/dataconcentrator/,f30e98
https://beagleboard.org/project/LinuxCNC/,1f026c
https://beagleboard.org/project/bbbandroid/,11c290
https://beagleboard.org/project/teensywall/,f88d9c
https://beagleboard.org/project/comred/,8e787e
https://beagleboard.org/project/TheDeck/,80279e
https://beagleboard.org/project/automation/,a57023
https://beagleboard.org/project/b3gcc/,5c36fc
https://beagleboard.org/project/restservice/,38930f
https://beagleboard.org/project/libbulldog/,dca387
https://beagleboard.org/project/beaglesnes/,55bc3b
https://beagleboard.org/project/trackingcape/,50e63d
https://beagleboard.org/project/FirstRobot/,9cf23e
https://beagleboard.org/project/BBB-GVS/,bcc7da
https://beagleboard.org/project/M2M/,b4cb61
https://beagleboard.org/project/doghouse/,f4d902
https://beagleboard.org/project/NinjaBlocks/,744d45
https://beagleboard.org/project/eqep_rotary_encoder/,571f67
https://beagleboard.org/project/bard/,eb0c49
https://beagleboard.org/project/Snoopy/,19d8d3
https://beagleboard.org/project/angstrom/,e3c0bb
https://beagleboard.org/project/blacklib/,785c69
https://beagleboard.org/project/AM/,71c1f8
https://beagleboard.org/project/OMAP+U-Boot+Utils/,7fb723
https://beagleboard.org/project/programming-bbb-book/,63aa64
https://beagleboard.org/project/minix-i2c/,c160e2
https://beagleboard.org/project/rowboat/,bf45c1
https://beagleboard.org/project/bad-to-the-bone/,8baede
https://beagleboard.org/project/Uboot+USB+gadget/,f88592
https://beagleboard.org/project/MotherBoneOne/,42abc5
https://beagleboard.org/project/RuneAudio/,464339
https://beagleboard.org/project/BBB_FreeBASIC+/,98bc9e
https://beagleboard.org/project/BeeDome/,c3e1ba
https://beagleboard.org/project/Sky+Drone+FPV/,173142
https://beagleboard.org/project/OBD-II+BBB/,b88568
https://beagleboard.org/project/titanarm/,4df894
https://beagleboard.org/project/cellular/,0aa4cd
https://beagleboard.org/project/HelenOS/,607478
https://beagleboard.org/project/IM-002/,e49b97
https://beagleboard.org/project/VTOS/,e4d6ff
https://beagleboard.org/project/EMMA/,132b76
https://beagleboard.org/project/robot+cleaner/,725df8
https://beagleboard.org/project/shark-detection/,a6d833
https://beagleboard.org/project/pristotrope/,7bf8b7
https://beagleboard.org/project/Beagle+Tomb/,f45f93
https://beagleboard.org/project/kinect+like+3D+camera/,79f450
https://beagleboard.org/project/BlindLeadingBlind/,f9f1c3
https://beagleboard.org/project/pandora/,59cb92
https://beagleboard.org/project/Xibo+For+BeagleBoard/,e022f0
https://beagleboard.org/project/Android+RIL+porting/,0936ae
https://beagleboard.org/project/ARM+Lguest/,3f4bdf
https://beagleboard.org/project/windows-embedded-bundle/,74aa9d
https://beagleboard.org/project/androidonbeagle/,282dc2
https://beagleboard.org/project/soniCube/,53fb7b
https://beagleboard.org/project/simulink/,ee3749
https://beagleboard.org/project/BuggyHero/,33db0a
https://beagleboard.org/project/Beagle+Vehicular+box./,93d2d1
https://beagleboard.org/project/BeagleforLearners/,dc5f27
https://beagleboard.org/project/FridgeAssist/,060b14
https://beagleboard.org/project/autoNurse/,c8b169
https://beagleboard.org/project/PCBFab/,bcb00e
https://beagleboard.org/project/sniffer-beagle/,3850d4
https://beagleboard.org/project/ombh/,a315ed
https://beagleboard.org/project/Beagleboard+Windows+CE6.0+R3/,4f7fdd
https://beagleboard.org/project/BeagleWalker/,66d7a6
https://beagleboard.org/project/sabayon/,752cf4
https://beagleboard.org/project/Storyboard+/,b170a9
https://beagleboard.org/project/Ethernet+expansion+board/,51cc60
https://beagleboard.org/project/H.264-based+2D-3D+conversion/,f6588e
https://beagleboard.org/project/Distant+Camera/,422314
https://beagleboard.org/project/Bonelib/,362a7b
https://beagleboard.org/project/X-Loader/,234e3f
https://beagleboard.org/project/GSTAS/,24ff75
https://beagleboard.org/project/Prototyping+Expansion+Board/,a35431
https://beagleboard.org/project/Buildroot+for+Beagleboard/,f6df82
https://beagleboard.org/project/Beagle+Guard/,64b0b8
https://beagleboard.org/project/Jukebox/,2fa8e8
https://beagleboard.org/project/Beagle+SecMon/,68d824
https://beagleboard.org/project/BeagleImager/,ab4f8d
https://beagleboard.org/project/ScramblerBeagle/,cb1444
https://beagleboard.org/project/eNurse/,b310c3
https://beagleboard.org/project/Beagle+HSS/,b0533d
https://beagleboard.org/project/autorobo/,7ece98
https://beagleboard.org/project/OSkitPort/,c9759f
https://beagleboard.org/project/Disko/,466a10
https://beagleboard.org/project/UPnP_AV_MediaServer/,c24750
https://beagleboard.org/project/travelbuddy/,b4f6b4
https://beagleboard.org/project/Math-Neon/,395c7d
https://beagleboard.org/project/ONAS/,a05c4f
https://beagleboard.org/project/Turk/,d1b608
https://beagleboard.org/project/beagle-synth/,ee2c25
https://beagleboard.org/project/BeagleUAV/,929eda
https://beagleboard.org/project/PortablePlateRec/,0025c2
https://beagleboard.org/project/SecureHome/,e0879e
https://beagleboard.org/project/cncplasma/,435595
https://beagleboard.org/project/yocto-project/,3e770a
https://beagleboard.org/project/bbb-lcd-fbtft-prebuilt/,8dea4d
https://beagleboard.org/project/Streaming+video+BBB/,b10b11
https://beagleboard.org/project/AV-Streamer/,be4eb1
https://beagleboard.org/project/rtklib/,a93bd0
https://beagleboard.org/project/beaglearcade/,4d83b1
https://beagleboard.org/project/XBMC/,253973
https://beagleboard.org/project/Serial+download/,607134
https://beagleboard.org/project/zigbee_ha/,9c5f72
https://beagleboard.org/project/fftw/,3469d0
https://beagleboard.org/project/nnControl/,086639
https://beagleboard.org/project/MediaCenter/,7f75dd
END_LINKS

my @entries = split(/\n/, $links);
foreach (@entries) {
	#print "$_\n";
	if (/\/([^\/]+)\/,(.*)$/) {
		my $proj = $1;
		my $id = $2;
		#print "$proj:$id\n";
		my $temp = $template;
		$temp =~ s/\[PROJ\]/$proj/;
		$temp =~ s/\[ID\]/$id/;
		print $temp;
	}
}
